// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contextual_card_list.proto

package com.android.settings.intelligence;

public final class ContextualCardProto {
  private ContextualCardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContextualCardListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.android.settings.intelligence.ContextualCardList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    java.util.List<com.android.settings.intelligence.ContextualCardProto.ContextualCard> 
        getCardList();
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    com.android.settings.intelligence.ContextualCardProto.ContextualCard getCard(int index);
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    int getCardCount();
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    java.util.List<? extends com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder> 
        getCardOrBuilderList();
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder getCardOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.android.settings.intelligence.ContextualCardList}
   */
  public  static final class ContextualCardList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.android.settings.intelligence.ContextualCardList)
      ContextualCardListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContextualCardList.newBuilder() to construct.
    private ContextualCardList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContextualCardList() {
      card_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContextualCardList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContextualCardList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                card_ = new java.util.ArrayList<com.android.settings.intelligence.ContextualCardProto.ContextualCard>();
                mutable_bitField0_ |= 0x00000001;
              }
              card_.add(
                  input.readMessage(com.android.settings.intelligence.ContextualCardProto.ContextualCard.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          card_ = java.util.Collections.unmodifiableList(card_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCardList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCardList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.settings.intelligence.ContextualCardProto.ContextualCardList.class, com.android.settings.intelligence.ContextualCardProto.ContextualCardList.Builder.class);
    }

    public static final int CARD_FIELD_NUMBER = 1;
    private java.util.List<com.android.settings.intelligence.ContextualCardProto.ContextualCard> card_;
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    public java.util.List<com.android.settings.intelligence.ContextualCardProto.ContextualCard> getCardList() {
      return card_;
    }
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    public java.util.List<? extends com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder> 
        getCardOrBuilderList() {
      return card_;
    }
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    public int getCardCount() {
      return card_.size();
    }
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    public com.android.settings.intelligence.ContextualCardProto.ContextualCard getCard(int index) {
      return card_.get(index);
    }
    /**
     * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
     */
    public com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder getCardOrBuilder(
        int index) {
      return card_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < card_.size(); i++) {
        output.writeMessage(1, card_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < card_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, card_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.android.settings.intelligence.ContextualCardProto.ContextualCardList)) {
        return super.equals(obj);
      }
      com.android.settings.intelligence.ContextualCardProto.ContextualCardList other = (com.android.settings.intelligence.ContextualCardProto.ContextualCardList) obj;

      if (!getCardList()
          .equals(other.getCardList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCardCount() > 0) {
        hash = (37 * hash) + CARD_FIELD_NUMBER;
        hash = (53 * hash) + getCardList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.android.settings.intelligence.ContextualCardProto.ContextualCardList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.android.settings.intelligence.ContextualCardList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.android.settings.intelligence.ContextualCardList)
        com.android.settings.intelligence.ContextualCardProto.ContextualCardListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCardList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCardList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.android.settings.intelligence.ContextualCardProto.ContextualCardList.class, com.android.settings.intelligence.ContextualCardProto.ContextualCardList.Builder.class);
      }

      // Construct using com.android.settings.intelligence.ContextualCardProto.ContextualCardList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCardFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (cardBuilder_ == null) {
          card_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cardBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCardList_descriptor;
      }

      @java.lang.Override
      public com.android.settings.intelligence.ContextualCardProto.ContextualCardList getDefaultInstanceForType() {
        return com.android.settings.intelligence.ContextualCardProto.ContextualCardList.getDefaultInstance();
      }

      @java.lang.Override
      public com.android.settings.intelligence.ContextualCardProto.ContextualCardList build() {
        com.android.settings.intelligence.ContextualCardProto.ContextualCardList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.android.settings.intelligence.ContextualCardProto.ContextualCardList buildPartial() {
        com.android.settings.intelligence.ContextualCardProto.ContextualCardList result = new com.android.settings.intelligence.ContextualCardProto.ContextualCardList(this);
        int from_bitField0_ = bitField0_;
        if (cardBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            card_ = java.util.Collections.unmodifiableList(card_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.card_ = card_;
        } else {
          result.card_ = cardBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.android.settings.intelligence.ContextualCardProto.ContextualCardList) {
          return mergeFrom((com.android.settings.intelligence.ContextualCardProto.ContextualCardList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.android.settings.intelligence.ContextualCardProto.ContextualCardList other) {
        if (other == com.android.settings.intelligence.ContextualCardProto.ContextualCardList.getDefaultInstance()) return this;
        if (cardBuilder_ == null) {
          if (!other.card_.isEmpty()) {
            if (card_.isEmpty()) {
              card_ = other.card_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCardIsMutable();
              card_.addAll(other.card_);
            }
            onChanged();
          }
        } else {
          if (!other.card_.isEmpty()) {
            if (cardBuilder_.isEmpty()) {
              cardBuilder_.dispose();
              cardBuilder_ = null;
              card_ = other.card_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cardBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCardFieldBuilder() : null;
            } else {
              cardBuilder_.addAllMessages(other.card_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.android.settings.intelligence.ContextualCardProto.ContextualCardList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.android.settings.intelligence.ContextualCardProto.ContextualCardList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.android.settings.intelligence.ContextualCardProto.ContextualCard> card_ =
        java.util.Collections.emptyList();
      private void ensureCardIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          card_ = new java.util.ArrayList<com.android.settings.intelligence.ContextualCardProto.ContextualCard>(card_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.android.settings.intelligence.ContextualCardProto.ContextualCard, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder, com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder> cardBuilder_;

      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public java.util.List<com.android.settings.intelligence.ContextualCardProto.ContextualCard> getCardList() {
        if (cardBuilder_ == null) {
          return java.util.Collections.unmodifiableList(card_);
        } else {
          return cardBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public int getCardCount() {
        if (cardBuilder_ == null) {
          return card_.size();
        } else {
          return cardBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard getCard(int index) {
        if (cardBuilder_ == null) {
          return card_.get(index);
        } else {
          return cardBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder setCard(
          int index, com.android.settings.intelligence.ContextualCardProto.ContextualCard value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardIsMutable();
          card_.set(index, value);
          onChanged();
        } else {
          cardBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder setCard(
          int index, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder builderForValue) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.set(index, builderForValue.build());
          onChanged();
        } else {
          cardBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder addCard(com.android.settings.intelligence.ContextualCardProto.ContextualCard value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardIsMutable();
          card_.add(value);
          onChanged();
        } else {
          cardBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder addCard(
          int index, com.android.settings.intelligence.ContextualCardProto.ContextualCard value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardIsMutable();
          card_.add(index, value);
          onChanged();
        } else {
          cardBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder addCard(
          com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder builderForValue) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.add(builderForValue.build());
          onChanged();
        } else {
          cardBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder addCard(
          int index, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder builderForValue) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.add(index, builderForValue.build());
          onChanged();
        } else {
          cardBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder addAllCard(
          java.lang.Iterable<? extends com.android.settings.intelligence.ContextualCardProto.ContextualCard> values) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, card_);
          onChanged();
        } else {
          cardBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder clearCard() {
        if (cardBuilder_ == null) {
          card_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cardBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public Builder removeCard(int index) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.remove(index);
          onChanged();
        } else {
          cardBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder getCardBuilder(
          int index) {
        return getCardFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder getCardOrBuilder(
          int index) {
        if (cardBuilder_ == null) {
          return card_.get(index);  } else {
          return cardBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public java.util.List<? extends com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder> 
           getCardOrBuilderList() {
        if (cardBuilder_ != null) {
          return cardBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(card_);
        }
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder addCardBuilder() {
        return getCardFieldBuilder().addBuilder(
            com.android.settings.intelligence.ContextualCardProto.ContextualCard.getDefaultInstance());
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder addCardBuilder(
          int index) {
        return getCardFieldBuilder().addBuilder(
            index, com.android.settings.intelligence.ContextualCardProto.ContextualCard.getDefaultInstance());
      }
      /**
       * <code>repeated .com.android.settings.intelligence.ContextualCard card = 1;</code>
       */
      public java.util.List<com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder> 
           getCardBuilderList() {
        return getCardFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.android.settings.intelligence.ContextualCardProto.ContextualCard, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder, com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder> 
          getCardFieldBuilder() {
        if (cardBuilder_ == null) {
          cardBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.android.settings.intelligence.ContextualCardProto.ContextualCard, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder, com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder>(
                  card_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        return cardBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.android.settings.intelligence.ContextualCardList)
    }

    // @@protoc_insertion_point(class_scope:com.android.settings.intelligence.ContextualCardList)
    private static final com.android.settings.intelligence.ContextualCardProto.ContextualCardList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.android.settings.intelligence.ContextualCardProto.ContextualCardList();
    }

    public static com.android.settings.intelligence.ContextualCardProto.ContextualCardList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContextualCardList>
        PARSER = new com.google.protobuf.AbstractParser<ContextualCardList>() {
      @java.lang.Override
      public ContextualCardList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContextualCardList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContextualCardList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContextualCardList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.android.settings.intelligence.ContextualCardProto.ContextualCardList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContextualCardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.android.settings.intelligence.ContextualCard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** Slice uri of the contextual card 
     * </pre>
     *
     * <code>optional string sliceUri = 1;</code>
     * @return Whether the sliceUri field is set.
     */
    boolean hasSliceUri();
    /**
     * <pre>
     ** Slice uri of the contextual card 
     * </pre>
     *
     * <code>optional string sliceUri = 1;</code>
     * @return The sliceUri.
     */
    java.lang.String getSliceUri();
    /**
     * <pre>
     ** Slice uri of the contextual card 
     * </pre>
     *
     * <code>optional string sliceUri = 1;</code>
     * @return The bytes for sliceUri.
     */
    com.google.protobuf.ByteString
        getSliceUriBytes();

    /**
     * <pre>
     ** Name of the card. It should be identical in every app 
     * </pre>
     *
     * <code>optional string cardName = 3;</code>
     * @return Whether the cardName field is set.
     */
    boolean hasCardName();
    /**
     * <pre>
     ** Name of the card. It should be identical in every app 
     * </pre>
     *
     * <code>optional string cardName = 3;</code>
     * @return The cardName.
     */
    java.lang.String getCardName();
    /**
     * <pre>
     ** Name of the card. It should be identical in every app 
     * </pre>
     *
     * <code>optional string cardName = 3;</code>
     * @return The bytes for cardName.
     */
    com.google.protobuf.ByteString
        getCardNameBytes();

    /**
     * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
     * @return Whether the cardCategory field is set.
     */
    boolean hasCardCategory();
    /**
     * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
     * @return The cardCategory.
     */
    com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category getCardCategory();

    /**
     * <code>optional double card_score = 5;</code>
     * @return Whether the cardScore field is set.
     */
    boolean hasCardScore();
    /**
     * <code>optional double card_score = 5;</code>
     * @return The cardScore.
     */
    double getCardScore();
  }
  /**
   * Protobuf type {@code com.android.settings.intelligence.ContextualCard}
   */
  public  static final class ContextualCard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.android.settings.intelligence.ContextualCard)
      ContextualCardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContextualCard.newBuilder() to construct.
    private ContextualCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContextualCard() {
      sliceUri_ = "";
      cardName_ = "";
      cardCategory_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContextualCard();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContextualCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sliceUri_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              cardName_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category value = com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cardCategory_ = rawValue;
              }
              break;
            }
            case 41: {
              bitField0_ |= 0x00000008;
              cardScore_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.settings.intelligence.ContextualCardProto.ContextualCard.class, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder.class);
    }

    /**
     * <pre>
     **
     * The category of a card: this is a hint for how a card should be collected,
     * ranked, and presented
     * </pre>
     *
     * Protobuf enum {@code com.android.settings.intelligence.ContextualCard.Category}
     */
    public enum Category
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <code>SUGGESTION = 1;</code>
       */
      SUGGESTION(1),
      /**
       * <code>POSSIBLE = 2;</code>
       */
      POSSIBLE(2),
      /**
       * <code>IMPORTANT = 3;</code>
       */
      IMPORTANT(3),
      /**
       * <code>DEFERRED_SETUP = 5;</code>
       */
      DEFERRED_SETUP(5),
      /**
       * <code>STICKY = 6;</code>
       */
      STICKY(6),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <code>SUGGESTION = 1;</code>
       */
      public static final int SUGGESTION_VALUE = 1;
      /**
       * <code>POSSIBLE = 2;</code>
       */
      public static final int POSSIBLE_VALUE = 2;
      /**
       * <code>IMPORTANT = 3;</code>
       */
      public static final int IMPORTANT_VALUE = 3;
      /**
       * <code>DEFERRED_SETUP = 5;</code>
       */
      public static final int DEFERRED_SETUP_VALUE = 5;
      /**
       * <code>STICKY = 6;</code>
       */
      public static final int STICKY_VALUE = 6;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Category valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Category forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return SUGGESTION;
          case 2: return POSSIBLE;
          case 3: return IMPORTANT;
          case 5: return DEFERRED_SETUP;
          case 6: return STICKY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Category>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Category> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Category>() {
              public Category findValueByNumber(int number) {
                return Category.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.android.settings.intelligence.ContextualCardProto.ContextualCard.getDescriptor().getEnumTypes().get(0);
      }

      private static final Category[] VALUES = values();

      public static Category valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Category(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.android.settings.intelligence.ContextualCard.Category)
    }

    private int bitField0_;
    public static final int SLICEURI_FIELD_NUMBER = 1;
    private volatile java.lang.Object sliceUri_;
    /**
     * <pre>
     ** Slice uri of the contextual card 
     * </pre>
     *
     * <code>optional string sliceUri = 1;</code>
     * @return Whether the sliceUri field is set.
     */
    public boolean hasSliceUri() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     ** Slice uri of the contextual card 
     * </pre>
     *
     * <code>optional string sliceUri = 1;</code>
     * @return The sliceUri.
     */
    public java.lang.String getSliceUri() {
      java.lang.Object ref = sliceUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sliceUri_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     ** Slice uri of the contextual card 
     * </pre>
     *
     * <code>optional string sliceUri = 1;</code>
     * @return The bytes for sliceUri.
     */
    public com.google.protobuf.ByteString
        getSliceUriBytes() {
      java.lang.Object ref = sliceUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sliceUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARDNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object cardName_;
    /**
     * <pre>
     ** Name of the card. It should be identical in every app 
     * </pre>
     *
     * <code>optional string cardName = 3;</code>
     * @return Whether the cardName field is set.
     */
    public boolean hasCardName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     ** Name of the card. It should be identical in every app 
     * </pre>
     *
     * <code>optional string cardName = 3;</code>
     * @return The cardName.
     */
    public java.lang.String getCardName() {
      java.lang.Object ref = cardName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cardName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     ** Name of the card. It should be identical in every app 
     * </pre>
     *
     * <code>optional string cardName = 3;</code>
     * @return The bytes for cardName.
     */
    public com.google.protobuf.ByteString
        getCardNameBytes() {
      java.lang.Object ref = cardName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARD_CATEGORY_FIELD_NUMBER = 4;
    private int cardCategory_;
    /**
     * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
     * @return Whether the cardCategory field is set.
     */
    public boolean hasCardCategory() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
     * @return The cardCategory.
     */
    public com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category getCardCategory() {
      @SuppressWarnings("deprecation")
      com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category result = com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category.valueOf(cardCategory_);
      return result == null ? com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category.DEFAULT : result;
    }

    public static final int CARD_SCORE_FIELD_NUMBER = 5;
    private double cardScore_;
    /**
     * <code>optional double card_score = 5;</code>
     * @return Whether the cardScore field is set.
     */
    public boolean hasCardScore() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double card_score = 5;</code>
     * @return The cardScore.
     */
    public double getCardScore() {
      return cardScore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sliceUri_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cardName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(4, cardCategory_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(5, cardScore_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sliceUri_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cardName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, cardCategory_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, cardScore_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.android.settings.intelligence.ContextualCardProto.ContextualCard)) {
        return super.equals(obj);
      }
      com.android.settings.intelligence.ContextualCardProto.ContextualCard other = (com.android.settings.intelligence.ContextualCardProto.ContextualCard) obj;

      if (hasSliceUri() != other.hasSliceUri()) return false;
      if (hasSliceUri()) {
        if (!getSliceUri()
            .equals(other.getSliceUri())) return false;
      }
      if (hasCardName() != other.hasCardName()) return false;
      if (hasCardName()) {
        if (!getCardName()
            .equals(other.getCardName())) return false;
      }
      if (hasCardCategory() != other.hasCardCategory()) return false;
      if (hasCardCategory()) {
        if (cardCategory_ != other.cardCategory_) return false;
      }
      if (hasCardScore() != other.hasCardScore()) return false;
      if (hasCardScore()) {
        if (java.lang.Double.doubleToLongBits(getCardScore())
            != java.lang.Double.doubleToLongBits(
                other.getCardScore())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSliceUri()) {
        hash = (37 * hash) + SLICEURI_FIELD_NUMBER;
        hash = (53 * hash) + getSliceUri().hashCode();
      }
      if (hasCardName()) {
        hash = (37 * hash) + CARDNAME_FIELD_NUMBER;
        hash = (53 * hash) + getCardName().hashCode();
      }
      if (hasCardCategory()) {
        hash = (37 * hash) + CARD_CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + cardCategory_;
      }
      if (hasCardScore()) {
        hash = (37 * hash) + CARD_SCORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCardScore()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.android.settings.intelligence.ContextualCardProto.ContextualCard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.android.settings.intelligence.ContextualCard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.android.settings.intelligence.ContextualCard)
        com.android.settings.intelligence.ContextualCardProto.ContextualCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCard_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.android.settings.intelligence.ContextualCardProto.ContextualCard.class, com.android.settings.intelligence.ContextualCardProto.ContextualCard.Builder.class);
      }

      // Construct using com.android.settings.intelligence.ContextualCardProto.ContextualCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sliceUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cardName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cardCategory_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        cardScore_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.android.settings.intelligence.ContextualCardProto.internal_static_com_android_settings_intelligence_ContextualCard_descriptor;
      }

      @java.lang.Override
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard getDefaultInstanceForType() {
        return com.android.settings.intelligence.ContextualCardProto.ContextualCard.getDefaultInstance();
      }

      @java.lang.Override
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard build() {
        com.android.settings.intelligence.ContextualCardProto.ContextualCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard buildPartial() {
        com.android.settings.intelligence.ContextualCardProto.ContextualCard result = new com.android.settings.intelligence.ContextualCardProto.ContextualCard(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sliceUri_ = sliceUri_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cardName_ = cardName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cardCategory_ = cardCategory_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cardScore_ = cardScore_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.android.settings.intelligence.ContextualCardProto.ContextualCard) {
          return mergeFrom((com.android.settings.intelligence.ContextualCardProto.ContextualCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.android.settings.intelligence.ContextualCardProto.ContextualCard other) {
        if (other == com.android.settings.intelligence.ContextualCardProto.ContextualCard.getDefaultInstance()) return this;
        if (other.hasSliceUri()) {
          bitField0_ |= 0x00000001;
          sliceUri_ = other.sliceUri_;
          onChanged();
        }
        if (other.hasCardName()) {
          bitField0_ |= 0x00000002;
          cardName_ = other.cardName_;
          onChanged();
        }
        if (other.hasCardCategory()) {
          setCardCategory(other.getCardCategory());
        }
        if (other.hasCardScore()) {
          setCardScore(other.getCardScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.android.settings.intelligence.ContextualCardProto.ContextualCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.android.settings.intelligence.ContextualCardProto.ContextualCard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sliceUri_ = "";
      /**
       * <pre>
       ** Slice uri of the contextual card 
       * </pre>
       *
       * <code>optional string sliceUri = 1;</code>
       * @return Whether the sliceUri field is set.
       */
      public boolean hasSliceUri() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       ** Slice uri of the contextual card 
       * </pre>
       *
       * <code>optional string sliceUri = 1;</code>
       * @return The sliceUri.
       */
      public java.lang.String getSliceUri() {
        java.lang.Object ref = sliceUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sliceUri_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** Slice uri of the contextual card 
       * </pre>
       *
       * <code>optional string sliceUri = 1;</code>
       * @return The bytes for sliceUri.
       */
      public com.google.protobuf.ByteString
          getSliceUriBytes() {
        java.lang.Object ref = sliceUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sliceUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** Slice uri of the contextual card 
       * </pre>
       *
       * <code>optional string sliceUri = 1;</code>
       * @param value The sliceUri to set.
       * @return This builder for chaining.
       */
      public Builder setSliceUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sliceUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** Slice uri of the contextual card 
       * </pre>
       *
       * <code>optional string sliceUri = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSliceUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sliceUri_ = getDefaultInstance().getSliceUri();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** Slice uri of the contextual card 
       * </pre>
       *
       * <code>optional string sliceUri = 1;</code>
       * @param value The bytes for sliceUri to set.
       * @return This builder for chaining.
       */
      public Builder setSliceUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sliceUri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cardName_ = "";
      /**
       * <pre>
       ** Name of the card. It should be identical in every app 
       * </pre>
       *
       * <code>optional string cardName = 3;</code>
       * @return Whether the cardName field is set.
       */
      public boolean hasCardName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       ** Name of the card. It should be identical in every app 
       * </pre>
       *
       * <code>optional string cardName = 3;</code>
       * @return The cardName.
       */
      public java.lang.String getCardName() {
        java.lang.Object ref = cardName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cardName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** Name of the card. It should be identical in every app 
       * </pre>
       *
       * <code>optional string cardName = 3;</code>
       * @return The bytes for cardName.
       */
      public com.google.protobuf.ByteString
          getCardNameBytes() {
        java.lang.Object ref = cardName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** Name of the card. It should be identical in every app 
       * </pre>
       *
       * <code>optional string cardName = 3;</code>
       * @param value The cardName to set.
       * @return This builder for chaining.
       */
      public Builder setCardName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cardName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** Name of the card. It should be identical in every app 
       * </pre>
       *
       * <code>optional string cardName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cardName_ = getDefaultInstance().getCardName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** Name of the card. It should be identical in every app 
       * </pre>
       *
       * <code>optional string cardName = 3;</code>
       * @param value The bytes for cardName to set.
       * @return This builder for chaining.
       */
      public Builder setCardNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cardName_ = value;
        onChanged();
        return this;
      }

      private int cardCategory_ = 0;
      /**
       * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
       * @return Whether the cardCategory field is set.
       */
      public boolean hasCardCategory() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
       * @return The cardCategory.
       */
      public com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category getCardCategory() {
        @SuppressWarnings("deprecation")
        com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category result = com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category.valueOf(cardCategory_);
        return result == null ? com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category.DEFAULT : result;
      }
      /**
       * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
       * @param value The cardCategory to set.
       * @return This builder for chaining.
       */
      public Builder setCardCategory(com.android.settings.intelligence.ContextualCardProto.ContextualCard.Category value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cardCategory_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.android.settings.intelligence.ContextualCard.Category card_category = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardCategory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cardCategory_ = 0;
        onChanged();
        return this;
      }

      private double cardScore_ ;
      /**
       * <code>optional double card_score = 5;</code>
       * @return Whether the cardScore field is set.
       */
      public boolean hasCardScore() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional double card_score = 5;</code>
       * @return The cardScore.
       */
      public double getCardScore() {
        return cardScore_;
      }
      /**
       * <code>optional double card_score = 5;</code>
       * @param value The cardScore to set.
       * @return This builder for chaining.
       */
      public Builder setCardScore(double value) {
        bitField0_ |= 0x00000008;
        cardScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double card_score = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardScore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cardScore_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.android.settings.intelligence.ContextualCard)
    }

    // @@protoc_insertion_point(class_scope:com.android.settings.intelligence.ContextualCard)
    private static final com.android.settings.intelligence.ContextualCardProto.ContextualCard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.android.settings.intelligence.ContextualCardProto.ContextualCard();
    }

    public static com.android.settings.intelligence.ContextualCardProto.ContextualCard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContextualCard>
        PARSER = new com.google.protobuf.AbstractParser<ContextualCard>() {
      @java.lang.Override
      public ContextualCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContextualCard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContextualCard> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContextualCard> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.android.settings.intelligence.ContextualCardProto.ContextualCard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_settings_intelligence_ContextualCardList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_settings_intelligence_ContextualCardList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_settings_intelligence_ContextualCard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_settings_intelligence_ContextualCard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032contextual_card_list.proto\022!com.androi" +
      "d.settings.intelligence\"U\n\022ContextualCar" +
      "dList\022?\n\004card\030\001 \003(\01321.com.android.settin" +
      "gs.intelligence.ContextualCard\"\201\002\n\016Conte" +
      "xtualCard\022\020\n\010sliceUri\030\001 \001(\t\022\020\n\010cardName\030" +
      "\003 \001(\t\022Q\n\rcard_category\030\004 \001(\0162:.com.andro" +
      "id.settings.intelligence.ContextualCard." +
      "Category\022\022\n\ncard_score\030\005 \001(\001\"d\n\010Category" +
      "\022\013\n\007DEFAULT\020\000\022\016\n\nSUGGESTION\020\001\022\014\n\010POSSIBL" +
      "E\020\002\022\r\n\tIMPORTANT\020\003\022\022\n\016DEFERRED_SETUP\020\005\022\n" +
      "\n\006STICKY\020\006B\025B\023ContextualCardProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_android_settings_intelligence_ContextualCardList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_android_settings_intelligence_ContextualCardList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_settings_intelligence_ContextualCardList_descriptor,
        new java.lang.String[] { "Card", });
    internal_static_com_android_settings_intelligence_ContextualCard_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_android_settings_intelligence_ContextualCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_settings_intelligence_ContextualCard_descriptor,
        new java.lang.String[] { "SliceUri", "CardName", "CardCategory", "CardScore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
