// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings_log_bridge.proto

package com.android.settings.intelligence;

public final class LogProto {
  private LogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SettingsLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.android.settings.intelligence.SettingsLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * Where this SettingsUIChange event comes from. For example, if
     * it's a PAGE_VISIBLE event, where the page is opened from.
     * </pre>
     *
     * <code>optional int32 attribution = 1;</code>
     * @return Whether the attribution field is set.
     */
    boolean hasAttribution();
    /**
     * <pre>
     **
     * Where this SettingsUIChange event comes from. For example, if
     * it's a PAGE_VISIBLE event, where the page is opened from.
     * </pre>
     *
     * <code>optional int32 attribution = 1;</code>
     * @return The attribution.
     */
    int getAttribution();

    /**
     * <pre>
     **
     * What the UI action is.
     * </pre>
     *
     * <code>optional int32 action = 2;</code>
     * @return Whether the action field is set.
     */
    boolean hasAction();
    /**
     * <pre>
     **
     * What the UI action is.
     * </pre>
     *
     * <code>optional int32 action = 2;</code>
     * @return The action.
     */
    int getAction();

    /**
     * <pre>
     **
     * Where the action is happening
     * </pre>
     *
     * <code>optional int32 page_id = 3;</code>
     * @return Whether the pageId field is set.
     */
    boolean hasPageId();
    /**
     * <pre>
     **
     * Where the action is happening
     * </pre>
     *
     * <code>optional int32 page_id = 3;</code>
     * @return The pageId.
     */
    int getPageId();

    /**
     * <pre>
     **
     * What preference changed in this event.
     * </pre>
     *
     * <code>optional string changed_preference_key = 4;</code>
     * @return Whether the changedPreferenceKey field is set.
     */
    boolean hasChangedPreferenceKey();
    /**
     * <pre>
     **
     * What preference changed in this event.
     * </pre>
     *
     * <code>optional string changed_preference_key = 4;</code>
     * @return The changedPreferenceKey.
     */
    java.lang.String getChangedPreferenceKey();
    /**
     * <pre>
     **
     * What preference changed in this event.
     * </pre>
     *
     * <code>optional string changed_preference_key = 4;</code>
     * @return The bytes for changedPreferenceKey.
     */
    com.google.protobuf.ByteString
        getChangedPreferenceKeyBytes();

    /**
     * <pre>
     **
     * The new value of the changed preference.
     * </pre>
     *
     * <code>optional int32 changed_preference_int_value = 5;</code>
     * @return Whether the changedPreferenceIntValue field is set.
     */
    boolean hasChangedPreferenceIntValue();
    /**
     * <pre>
     **
     * The new value of the changed preference.
     * </pre>
     *
     * <code>optional int32 changed_preference_int_value = 5;</code>
     * @return The changedPreferenceIntValue.
     */
    int getChangedPreferenceIntValue();

    /**
     * <pre>
     **
     * The timestamp of a log event
     * </pre>
     *
     * <code>optional string timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <pre>
     **
     * The timestamp of a log event
     * </pre>
     *
     * <code>optional string timestamp = 6;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     **
     * The timestamp of a log event
     * </pre>
     *
     * <code>optional string timestamp = 6;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();
  }
  /**
   * Protobuf type {@code com.android.settings.intelligence.SettingsLog}
   */
  public  static final class SettingsLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.android.settings.intelligence.SettingsLog)
      SettingsLogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SettingsLog.newBuilder() to construct.
    private SettingsLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SettingsLog() {
      changedPreferenceKey_ = "";
      timestamp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SettingsLog();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SettingsLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              attribution_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              action_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              changedPreferenceKey_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              changedPreferenceIntValue_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              timestamp_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.settings.intelligence.LogProto.internal_static_com_android_settings_intelligence_SettingsLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.settings.intelligence.LogProto.internal_static_com_android_settings_intelligence_SettingsLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.settings.intelligence.LogProto.SettingsLog.class, com.android.settings.intelligence.LogProto.SettingsLog.Builder.class);
    }

    private int bitField0_;
    public static final int ATTRIBUTION_FIELD_NUMBER = 1;
    private int attribution_;
    /**
     * <pre>
     **
     * Where this SettingsUIChange event comes from. For example, if
     * it's a PAGE_VISIBLE event, where the page is opened from.
     * </pre>
     *
     * <code>optional int32 attribution = 1;</code>
     * @return Whether the attribution field is set.
     */
    public boolean hasAttribution() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     **
     * Where this SettingsUIChange event comes from. For example, if
     * it's a PAGE_VISIBLE event, where the page is opened from.
     * </pre>
     *
     * <code>optional int32 attribution = 1;</code>
     * @return The attribution.
     */
    public int getAttribution() {
      return attribution_;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <pre>
     **
     * What the UI action is.
     * </pre>
     *
     * <code>optional int32 action = 2;</code>
     * @return Whether the action field is set.
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     **
     * What the UI action is.
     * </pre>
     *
     * <code>optional int32 action = 2;</code>
     * @return The action.
     */
    public int getAction() {
      return action_;
    }

    public static final int PAGE_ID_FIELD_NUMBER = 3;
    private int pageId_;
    /**
     * <pre>
     **
     * Where the action is happening
     * </pre>
     *
     * <code>optional int32 page_id = 3;</code>
     * @return Whether the pageId field is set.
     */
    public boolean hasPageId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     **
     * Where the action is happening
     * </pre>
     *
     * <code>optional int32 page_id = 3;</code>
     * @return The pageId.
     */
    public int getPageId() {
      return pageId_;
    }

    public static final int CHANGED_PREFERENCE_KEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object changedPreferenceKey_;
    /**
     * <pre>
     **
     * What preference changed in this event.
     * </pre>
     *
     * <code>optional string changed_preference_key = 4;</code>
     * @return Whether the changedPreferenceKey field is set.
     */
    public boolean hasChangedPreferenceKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     **
     * What preference changed in this event.
     * </pre>
     *
     * <code>optional string changed_preference_key = 4;</code>
     * @return The changedPreferenceKey.
     */
    public java.lang.String getChangedPreferenceKey() {
      java.lang.Object ref = changedPreferenceKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          changedPreferenceKey_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     **
     * What preference changed in this event.
     * </pre>
     *
     * <code>optional string changed_preference_key = 4;</code>
     * @return The bytes for changedPreferenceKey.
     */
    public com.google.protobuf.ByteString
        getChangedPreferenceKeyBytes() {
      java.lang.Object ref = changedPreferenceKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        changedPreferenceKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANGED_PREFERENCE_INT_VALUE_FIELD_NUMBER = 5;
    private int changedPreferenceIntValue_;
    /**
     * <pre>
     **
     * The new value of the changed preference.
     * </pre>
     *
     * <code>optional int32 changed_preference_int_value = 5;</code>
     * @return Whether the changedPreferenceIntValue field is set.
     */
    public boolean hasChangedPreferenceIntValue() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     **
     * The new value of the changed preference.
     * </pre>
     *
     * <code>optional int32 changed_preference_int_value = 5;</code>
     * @return The changedPreferenceIntValue.
     */
    public int getChangedPreferenceIntValue() {
      return changedPreferenceIntValue_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     **
     * The timestamp of a log event
     * </pre>
     *
     * <code>optional string timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     **
     * The timestamp of a log event
     * </pre>
     *
     * <code>optional string timestamp = 6;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     **
     * The timestamp of a log event
     * </pre>
     *
     * <code>optional string timestamp = 6;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, attribution_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, action_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, pageId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, changedPreferenceKey_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, changedPreferenceIntValue_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, attribution_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, action_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, changedPreferenceKey_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, changedPreferenceIntValue_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.android.settings.intelligence.LogProto.SettingsLog)) {
        return super.equals(obj);
      }
      com.android.settings.intelligence.LogProto.SettingsLog other = (com.android.settings.intelligence.LogProto.SettingsLog) obj;

      if (hasAttribution() != other.hasAttribution()) return false;
      if (hasAttribution()) {
        if (getAttribution()
            != other.getAttribution()) return false;
      }
      if (hasAction() != other.hasAction()) return false;
      if (hasAction()) {
        if (getAction()
            != other.getAction()) return false;
      }
      if (hasPageId() != other.hasPageId()) return false;
      if (hasPageId()) {
        if (getPageId()
            != other.getPageId()) return false;
      }
      if (hasChangedPreferenceKey() != other.hasChangedPreferenceKey()) return false;
      if (hasChangedPreferenceKey()) {
        if (!getChangedPreferenceKey()
            .equals(other.getChangedPreferenceKey())) return false;
      }
      if (hasChangedPreferenceIntValue() != other.hasChangedPreferenceIntValue()) return false;
      if (hasChangedPreferenceIntValue()) {
        if (getChangedPreferenceIntValue()
            != other.getChangedPreferenceIntValue()) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttribution()) {
        hash = (37 * hash) + ATTRIBUTION_FIELD_NUMBER;
        hash = (53 * hash) + getAttribution();
      }
      if (hasAction()) {
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + getAction();
      }
      if (hasPageId()) {
        hash = (37 * hash) + PAGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPageId();
      }
      if (hasChangedPreferenceKey()) {
        hash = (37 * hash) + CHANGED_PREFERENCE_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getChangedPreferenceKey().hashCode();
      }
      if (hasChangedPreferenceIntValue()) {
        hash = (37 * hash) + CHANGED_PREFERENCE_INT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getChangedPreferenceIntValue();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.settings.intelligence.LogProto.SettingsLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.android.settings.intelligence.LogProto.SettingsLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.android.settings.intelligence.SettingsLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.android.settings.intelligence.SettingsLog)
        com.android.settings.intelligence.LogProto.SettingsLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.android.settings.intelligence.LogProto.internal_static_com_android_settings_intelligence_SettingsLog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.android.settings.intelligence.LogProto.internal_static_com_android_settings_intelligence_SettingsLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.android.settings.intelligence.LogProto.SettingsLog.class, com.android.settings.intelligence.LogProto.SettingsLog.Builder.class);
      }

      // Construct using com.android.settings.intelligence.LogProto.SettingsLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        attribution_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        changedPreferenceKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        changedPreferenceIntValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.android.settings.intelligence.LogProto.internal_static_com_android_settings_intelligence_SettingsLog_descriptor;
      }

      @java.lang.Override
      public com.android.settings.intelligence.LogProto.SettingsLog getDefaultInstanceForType() {
        return com.android.settings.intelligence.LogProto.SettingsLog.getDefaultInstance();
      }

      @java.lang.Override
      public com.android.settings.intelligence.LogProto.SettingsLog build() {
        com.android.settings.intelligence.LogProto.SettingsLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.android.settings.intelligence.LogProto.SettingsLog buildPartial() {
        com.android.settings.intelligence.LogProto.SettingsLog result = new com.android.settings.intelligence.LogProto.SettingsLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.attribution_ = attribution_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.action_ = action_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pageId_ = pageId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.changedPreferenceKey_ = changedPreferenceKey_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.changedPreferenceIntValue_ = changedPreferenceIntValue_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.android.settings.intelligence.LogProto.SettingsLog) {
          return mergeFrom((com.android.settings.intelligence.LogProto.SettingsLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.android.settings.intelligence.LogProto.SettingsLog other) {
        if (other == com.android.settings.intelligence.LogProto.SettingsLog.getDefaultInstance()) return this;
        if (other.hasAttribution()) {
          setAttribution(other.getAttribution());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasPageId()) {
          setPageId(other.getPageId());
        }
        if (other.hasChangedPreferenceKey()) {
          bitField0_ |= 0x00000008;
          changedPreferenceKey_ = other.changedPreferenceKey_;
          onChanged();
        }
        if (other.hasChangedPreferenceIntValue()) {
          setChangedPreferenceIntValue(other.getChangedPreferenceIntValue());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000020;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.android.settings.intelligence.LogProto.SettingsLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.android.settings.intelligence.LogProto.SettingsLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int attribution_ ;
      /**
       * <pre>
       **
       * Where this SettingsUIChange event comes from. For example, if
       * it's a PAGE_VISIBLE event, where the page is opened from.
       * </pre>
       *
       * <code>optional int32 attribution = 1;</code>
       * @return Whether the attribution field is set.
       */
      public boolean hasAttribution() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       **
       * Where this SettingsUIChange event comes from. For example, if
       * it's a PAGE_VISIBLE event, where the page is opened from.
       * </pre>
       *
       * <code>optional int32 attribution = 1;</code>
       * @return The attribution.
       */
      public int getAttribution() {
        return attribution_;
      }
      /**
       * <pre>
       **
       * Where this SettingsUIChange event comes from. For example, if
       * it's a PAGE_VISIBLE event, where the page is opened from.
       * </pre>
       *
       * <code>optional int32 attribution = 1;</code>
       * @param value The attribution to set.
       * @return This builder for chaining.
       */
      public Builder setAttribution(int value) {
        bitField0_ |= 0x00000001;
        attribution_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * Where this SettingsUIChange event comes from. For example, if
       * it's a PAGE_VISIBLE event, where the page is opened from.
       * </pre>
       *
       * <code>optional int32 attribution = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttribution() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attribution_ = 0;
        onChanged();
        return this;
      }

      private int action_ ;
      /**
       * <pre>
       **
       * What the UI action is.
       * </pre>
       *
       * <code>optional int32 action = 2;</code>
       * @return Whether the action field is set.
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       **
       * What the UI action is.
       * </pre>
       *
       * <code>optional int32 action = 2;</code>
       * @return The action.
       */
      public int getAction() {
        return action_;
      }
      /**
       * <pre>
       **
       * What the UI action is.
       * </pre>
       *
       * <code>optional int32 action = 2;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(int value) {
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * What the UI action is.
       * </pre>
       *
       * <code>optional int32 action = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = 0;
        onChanged();
        return this;
      }

      private int pageId_ ;
      /**
       * <pre>
       **
       * Where the action is happening
       * </pre>
       *
       * <code>optional int32 page_id = 3;</code>
       * @return Whether the pageId field is set.
       */
      public boolean hasPageId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       **
       * Where the action is happening
       * </pre>
       *
       * <code>optional int32 page_id = 3;</code>
       * @return The pageId.
       */
      public int getPageId() {
        return pageId_;
      }
      /**
       * <pre>
       **
       * Where the action is happening
       * </pre>
       *
       * <code>optional int32 page_id = 3;</code>
       * @param value The pageId to set.
       * @return This builder for chaining.
       */
      public Builder setPageId(int value) {
        bitField0_ |= 0x00000004;
        pageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * Where the action is happening
       * </pre>
       *
       * <code>optional int32 page_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object changedPreferenceKey_ = "";
      /**
       * <pre>
       **
       * What preference changed in this event.
       * </pre>
       *
       * <code>optional string changed_preference_key = 4;</code>
       * @return Whether the changedPreferenceKey field is set.
       */
      public boolean hasChangedPreferenceKey() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       **
       * What preference changed in this event.
       * </pre>
       *
       * <code>optional string changed_preference_key = 4;</code>
       * @return The changedPreferenceKey.
       */
      public java.lang.String getChangedPreferenceKey() {
        java.lang.Object ref = changedPreferenceKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            changedPreferenceKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * What preference changed in this event.
       * </pre>
       *
       * <code>optional string changed_preference_key = 4;</code>
       * @return The bytes for changedPreferenceKey.
       */
      public com.google.protobuf.ByteString
          getChangedPreferenceKeyBytes() {
        java.lang.Object ref = changedPreferenceKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          changedPreferenceKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * What preference changed in this event.
       * </pre>
       *
       * <code>optional string changed_preference_key = 4;</code>
       * @param value The changedPreferenceKey to set.
       * @return This builder for chaining.
       */
      public Builder setChangedPreferenceKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        changedPreferenceKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * What preference changed in this event.
       * </pre>
       *
       * <code>optional string changed_preference_key = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangedPreferenceKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        changedPreferenceKey_ = getDefaultInstance().getChangedPreferenceKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * What preference changed in this event.
       * </pre>
       *
       * <code>optional string changed_preference_key = 4;</code>
       * @param value The bytes for changedPreferenceKey to set.
       * @return This builder for chaining.
       */
      public Builder setChangedPreferenceKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        changedPreferenceKey_ = value;
        onChanged();
        return this;
      }

      private int changedPreferenceIntValue_ ;
      /**
       * <pre>
       **
       * The new value of the changed preference.
       * </pre>
       *
       * <code>optional int32 changed_preference_int_value = 5;</code>
       * @return Whether the changedPreferenceIntValue field is set.
       */
      public boolean hasChangedPreferenceIntValue() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       **
       * The new value of the changed preference.
       * </pre>
       *
       * <code>optional int32 changed_preference_int_value = 5;</code>
       * @return The changedPreferenceIntValue.
       */
      public int getChangedPreferenceIntValue() {
        return changedPreferenceIntValue_;
      }
      /**
       * <pre>
       **
       * The new value of the changed preference.
       * </pre>
       *
       * <code>optional int32 changed_preference_int_value = 5;</code>
       * @param value The changedPreferenceIntValue to set.
       * @return This builder for chaining.
       */
      public Builder setChangedPreferenceIntValue(int value) {
        bitField0_ |= 0x00000010;
        changedPreferenceIntValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The new value of the changed preference.
       * </pre>
       *
       * <code>optional int32 changed_preference_int_value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangedPreferenceIntValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        changedPreferenceIntValue_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       **
       * The timestamp of a log event
       * </pre>
       *
       * <code>optional string timestamp = 6;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       **
       * The timestamp of a log event
       * </pre>
       *
       * <code>optional string timestamp = 6;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * The timestamp of a log event
       * </pre>
       *
       * <code>optional string timestamp = 6;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * The timestamp of a log event
       * </pre>
       *
       * <code>optional string timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The timestamp of a log event
       * </pre>
       *
       * <code>optional string timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The timestamp of a log event
       * </pre>
       *
       * <code>optional string timestamp = 6;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.android.settings.intelligence.SettingsLog)
    }

    // @@protoc_insertion_point(class_scope:com.android.settings.intelligence.SettingsLog)
    private static final com.android.settings.intelligence.LogProto.SettingsLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.android.settings.intelligence.LogProto.SettingsLog();
    }

    public static com.android.settings.intelligence.LogProto.SettingsLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SettingsLog>
        PARSER = new com.google.protobuf.AbstractParser<SettingsLog>() {
      @java.lang.Override
      public SettingsLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SettingsLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SettingsLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SettingsLog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.android.settings.intelligence.LogProto.SettingsLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_android_settings_intelligence_SettingsLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_android_settings_intelligence_SettingsLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031settings_log_bridge.proto\022!com.android" +
      ".settings.intelligence\"\234\001\n\013SettingsLog\022\023" +
      "\n\013attribution\030\001 \001(\005\022\016\n\006action\030\002 \001(\005\022\017\n\007p" +
      "age_id\030\003 \001(\005\022\036\n\026changed_preference_key\030\004" +
      " \001(\t\022$\n\034changed_preference_int_value\030\005 \001" +
      "(\005\022\021\n\ttimestamp\030\006 \001(\tB\nB\010LogProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_android_settings_intelligence_SettingsLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_android_settings_intelligence_SettingsLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_android_settings_intelligence_SettingsLog_descriptor,
        new java.lang.String[] { "Attribution", "Action", "PageId", "ChangedPreferenceKey", "ChangedPreferenceIntValue", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
